# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
    ROOT: INFO
    '[com.kuflow]': INFO

spring:
  application:
    name: KuFlow Engine Worker Sample Email
  profiles:
    default: dev
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: detect

feign:
  autoconfiguration:
    jackson:
      enabled: true

# ===================================================================
# Application specific properties
# ===================================================================
#application:
