# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  mail:
    host: FILL_ME
    port: FILL_ME
    username: FILL_ME
    password: FILL_ME_SECRET
    test-connection: true
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.auth: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

kuflow:
  activity:
    kuflow:
      endpoint: http://kuflow-server.kuflow-server.svc.cluster.local:8080/apis/external/v1
      application-id: FILL_ME
      password: FILL_ME_SECRET

# ===================================================================
# Application specific properties
# ===================================================================
application:
  temporal:
      namespace: FILL_ME
      kuflow-queue: KUFLOW_TASK_QUEUE
      target: engine.kuflow.com:443
      mutual-tls:
        ca-data: FILL_ME_SECRET
        cert-data: FILL_ME_SECRET
        key-data: FILL_ME_SECRET
